window.AMAZONIA_CATALOG = [
  {
    id: "gbif-species-occurrences",
    title: "GBIF Species Occurrence Data",
    provider: "Global Biodiversity Information Facility (GBIF)",
    category: "Forest & biodiversity",
    coverage: "Global — subsettable",
    formats: ["API", "Darwin Core Archive", "CSV"],
    access: "Publicly available",
    kind: "Data portal",
    description: "A global aggregator of species occurrence records \u2014 museum specimens, citizen-science observations, and survey data \u2014 searchable and filterable to the Amazon basin.",
    url: "https://www.gbif.org/",
    checked: "2026-07-14"
  },
  {
    id: "specieslink-network",
    title: "speciesLink Network",
    provider: "CRIA (Centro de Refer\u00eancia em Informa\u00e7\u00e3o Ambiental)",
    category: "Forest & biodiversity",
    coverage: "Brazil",
    formats: ["API", "CSV"],
    access: "Publicly available",
    kind: "Data portal",
    description: "A Brazilian biodiversity data network aggregating occurrence records for plants, animals, fungi, and microorganisms, enriched with images and land-use context for each collection site.",
    url: "https://specieslink.net/",
    checked: "2026-07-14"
  },
  {
    id: "ana-hidroweb",
    title: "Hidroweb \u2014 National Hydrometeorological Network",
    provider: "Ag\u00eancia Nacional de \u00c1guas e Saneamento B\u00e1sico (ANA)",
    category: "Climate, water & air",
    coverage: "Brazil",
    formats: ["CSV", "API"],
    access: "Publicly available",
    kind: "Data portal",
    description: "Station-level river level, streamflow, rainfall, and water-quality records from Brazil's National Hydrometeorological Network, run by the federal water agency.",
    url: "https://www.snirh.gov.br/hidroweb",
    checked: "2026-07-14"
  },
  {
    id: "inmet-bdmep",
    title: "BDMEP \u2014 Historical Meteorological Database",
    provider: "Instituto Nacional de Meteorologia (INMET)",
    category: "Climate, water & air",
    coverage: "Brazil",
    formats: ["CSV"],
    access: "Provider terms apply",
    kind: "Data portal",
    description: "Daily historical weather station records for Brazil since 2000 \u2014 temperature, rainfall, humidity, and wind \u2014 searchable by station or map.",
    url: "https://bdmep.inmet.gov.br/",
    checked: "2026-07-14"
  },
  {
    id: "mapbiomas-brasil",
    title: "MapBiomas Land Cover & Use Maps",
    provider: "MapBiomas (multi-institutional collaborative network)",
    category: "Land use & infrastructure",
    coverage: "Brazil",
    formats: ["GeoTIFF", "Google Earth Engine"],
    access: "Provider terms apply",
    kind: "Explorer",
    description: "Annual land cover and land-use maps for Brazil since 1985, built from satellite image classification, tracking deforestation, fire, and vegetation change by year and biome.",
    url: "https://brasil.mapbiomas.org/en/",
    checked: "2026-07-14"
  },
  {
    id: "inpe-terrabrasilis",
    title: "TerraBrasilis \u2014 PRODES & DETER Deforestation Monitoring",
    provider: "Instituto Nacional de Pesquisas Espaciais (INPE)",
    category: "Land use & infrastructure",
    coverage: "Brazil",
    formats: ["Shapefile", "GeoTIFF", "WMS/WFS"],
    access: "Provider terms apply",
    kind: "Explorer",
    description: "Brazil's official satellite-based deforestation monitoring system, publishing annual clear-cut mapping (PRODES) and near-real-time alerts (DETER) for the Legal Amazon and other biomes.",
    url: "https://terrabrasilis.dpi.inpe.br/en/home-page/",
    checked: "2026-07-14"
  },
  {
    id: "funai-terras-indigenas",
    title: "FUNAI Indigenous Territories Geodata",
    provider: "Funda\u00e7\u00e3o Nacional dos Povos Ind\u00edgenas (FUNAI)",
    category: "Peoples, territories & culture",
    coverage: "Brazil",
    formats: ["Shapefile", "KML", "CSV"],
    access: "Provider terms apply",
    kind: "Download",
    description: "Monthly-updated geospatial boundaries for Brazil's indigenous territories, villages, and regional coordination areas, from the federal indigenous affairs agency's mapping unit.",
    url: "https://www.gov.br/funai/pt-br/atuacao/terras-indigenas/geoprocessamento-e-mapas",
    checked: "2026-07-14"
  },
  {
    id: "isa-terras-indigenas",
    title: "Terras Ind\u00edgenas no Brasil",
    provider: "Instituto Socioambiental (ISA)",
    category: "Peoples, territories & culture",
    coverage: "Brazil",
    formats: ["HTML", "PDF"],
    access: "Provider terms apply",
    kind: "Explorer",
    description: "An independent, long-running database profiling Indigenous territories across Brazil \u2014 legal status, location, population, and news \u2014 maintained by a civil-society organization since the 1980s.",
    url: "https://terrasindigenas.org.br/",
    checked: "2026-07-14"
  },
  {
    id: "ibge-cidades",
    title: "IBGE Cidades",
    provider: "Instituto Brasileiro de Geografia e Estat\u00edstica (IBGE)",
    category: "Society, health & livelihoods",
    coverage: "Brazil",
    formats: ["HTML", "CSV"],
    access: "Publicly available",
    kind: "Explorer",
    description: "Official municipal and state-level statistics for Brazil \u2014 population, economy, education, and health indicators \u2014 searchable by place, from the national statistics institute.",
    url: "https://cidades.ibge.gov.br/",
    checked: "2026-07-14"
  },
  {
    id: "datasus-tabnet",
    title: "DATASUS TABNET Health Information",
    provider: "DATASUS, Minist\u00e9rio da Sa\u00fade",
    category: "Society, health & livelihoods",
    coverage: "Brazil",
    formats: ["CSV"],
    access: "Provider terms apply",
    kind: "Explorer",
    description: "An interactive tabulation tool for Brazil's public health system data \u2014 mortality, births, morbidity, and health-facility records \u2014 built by the Ministry of Health.",
    url: "https://datasus.saude.gov.br/informacoes-de-saude-tabnet/",
    checked: "2026-07-14"
  },
  {
    id: "icmbio-dados-geoespaciais",
    title: "ICMBio Protected Areas Geodata",
    provider: "Instituto Chico Mendes de Conserva\u00e7\u00e3o da Biodiversidade (ICMBio)",
    category: "Governance, rights & safeguards",
    coverage: "Brazil",
    formats: ["Shapefile", "KMZ"],
    access: "Dataset-specific license",
    kind: "Download",
    description: "Official boundary data for Brazil's federally managed protected areas, including national parks and biological reserves, published under an open data license by the agency that administers them.",
    url: "https://www.gov.br/icmbio/pt-br/assuntos/dados_geoespaciais",
    checked: "2026-07-14"
  },
  {
    id: "raisg-maps",
    title: "RAISG Amazon Maps",
    provider: "Red Amaz\u00f3nica de Informaci\u00f3n Socioambiental Georreferenciada (RAISG)",
    category: "Governance, rights & safeguards",
    coverage: "Pan-Amazon",
    formats: ["Shapefile", "Web map"],
    access: "Provider terms apply",
    kind: "Explorer",
    description: "Pan-Amazon geospatial data on indigenous territories, protected natural areas, infrastructure projects, and resource-extraction concessions, compiled by a nine-country civil-society network.",
    url: "https://www.raisg.org/en/maps/",
    checked: "2026-07-14"
  }
];
